import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>FUDO</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.png" />
			</Head>
			<main>
				<h1>Subscribe Zainkeepscode</h1>
			</main>
		</div>
	);
}
